### ISSUE TITLE
Eraser tool not working in negative height and width. 

### ISSUE THREAD

**Issue by SoumyaCO** [SoumyaCO/Collaboard#5]
When erasing something backward (i.e. negative height and width) the highlighted portion is persistent, and also not erasing. 

## Steps to reproduce:
1. Draw something on canvas. 
2. Try to erase some part of it using the eraser tool. 
3. Start erasing from the bottom-right corner to the top-right corner 
4. Watch it's not erasing.

**Comment by BlackHeart786** [comment]
fixed that issue in pr no 4

**Comment by SoumyaCO** [comment]
Okay, closing this issue
